### ISSUE TITLE
本番環境でのみ、sliceに失敗する

### ISSUE THREAD

**Issue by taku1417** [taku1417/nullpo-bot#33]
https://github.com/taku1417/nullpo-bot/blob/93199036372a01c4c4dcd139cc528100b30554ea/nullpobot.js#L484
ローカル環境では何故か成功する...

エラー文↓
TypeError: Cannot read properties of undefined (reading 'slice')
    at /app/nullpobot.js:484:48
    at _Collection.filter (/app/node_modules/@discordjs/collection/dist/index.js:207:11)
    at Timeout._onTimeout (/app/nullpobot.js:484:27)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Comment by taku1417** [comment]
sliceがundefinedになってるからch.nameがnullとかになってる？
けど、ローカルだと成功するためマジでよく分からん...

**Comment by taku1417** [comment]
もしかして:実行順
分割とか試してみる

**Comment by taku1417** [comment]
実行順とか関係なかった
恐らくチャンネルがキャッシュされていないのが問題...
guildごとfetchしても良いが、今後要素が増えた際に厄介になりそうな気もしなくもない
カテゴリのみをfetchできればいいが余計な文字列が増えるため見づらくなってしまう...。
原因は判明したのでどう解決するかはゆっくり考える

**Comment by taku1417** [comment]
vcの出入りをVCJoinLeaveCheck.jsでキャッチし、ログとして出力した後に失敗していることが分かった。
よく分かんねぇ...。

**Comment by taku1417** [comment]
本格運用する可能性が出てきたためdatabaseよりも優先しないといけない...

**Comment by taku1417** [comment]
原因が完全に分かったかもしれない。
エラー内容にtimeoutとあるのだが、恐らくチャンネルを全検索しているのが原因(ばか)。
ギルドを絞ったり、カテゴリで絞ったり(出来るかは不明)などすればほぼ確実になるとは思う。
それか、dbに作ったチャンネルのIDを記録しておいて、それを元にfetch、あとは今の処理をすればいい。

なお、別原因でtimeoutするほどの探索量になっていて、その問題を排除したため現時点では動くようになった。
故に当面は問題なく動くと思われる。だが抜本的な解決にはなっていないため、引き続き注力する。

**Comment by taku1417** [comment]
72177b6e9d2597406c7c948bf6ed4bd69b10b6d2 にてエラー箇所の処理を2行に分けた。
docやdjs日本のscrapboxを見る限り問題ない記述のようだが、intervalに入れているせいで発生しているのだろうか。
10分経ち2回ほど動いているのを見たが問題なさそう。heroku環境のため1日エラーを吐かなかったら問題ないと見て解決ということにしたい。

**Comment by taku1417** [comment]
コメントを残すのを忘れていた...。
https://github.com/taku1417/nullpo-bot/blob/570b6b7dbf1c76ee6c905957daccd590b06b016a/nullpobot.js#L491
上のように変更することで対応。原因としては、キャッシュサイズが増えたからなのか負荷が増えていったからなのか分からないが、channel.nameをmatchで使えるようにするため、Stringにキャストするのに時間がかかり、intervalの時間制限に引っかかっていた(と思われる)。
明示的にStringにキャストすることで、一度matchまでいってString必要だ！キャストォォォ！！ってやらなくてもよくなったのが時短になり解決につながったのだろうか。
interval外であったらtimeoutでない通常のエラートレースが出ていたのかもしれない。その場合は時間は関係なく、ただただStringになってなかっただけだろう。チャンネル数が少ない時は動いていたのがよく分からんが。
どちらにしろ、やや負荷のかかる作業ではありそう...。今後エラーを出し始めた際、コードを簡素化したり、性能の良いdynoに変更したりするなどで対応を迫られることになるかもしれない。

ひとまず、エラーはずっと出ていないので解決としておく。
